targetNamespace: ''
parameters: {}
packages:
  - name: redirector
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: go
        binary: false
        main: ''
        runtime: 'nodejs:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}